In [1]:
from utility_bfvariater import *
import utility_common as common

# creat a BF variater
er = BFVariater()

# 1. Central Value

In [4]:
def saveCentralValues(er):
    print( "save conteral values")

    contralValue = []
    for i in range(4):

        ndata = er.ndata[i]
        nmcbg = er.nmcbg[i].dot(np.ones(3))
        nfake = er.nfake[i]
        a = np.sum(er.a[i] * er.ca, axis=1)

        slv0 = BFSolver3D(a)
        br0 = slv0.solveQuadEqn(slv0.setMeasuredX(nData=ndata, nMcbg=nmcbg+nfake))
        contralValue.append(br0)
    contralValue = np.array(contralValue).reshape(12)

    baseDir = common.getBaseDirectory() 

    print(contralValue)

    np.save(baseDir+'/data/combine/centralValue',contralValue)
saveCentralValues(er)

save conteral values
[0.10956422 0.10807829 0.10339244 0.1120037  0.10977927 0.10359739
 0.10504756 0.10789798 0.1039401  0.10884808 0.1095145  0.10423655]


# 2. uncertainty

### 2.1 Statistical Uncertainty

In [5]:
def saveStatError(er):
    print( "relative statistical uncertainty [%]")

    stat_sigma, stat_covar = [],[]

    for source in ["data","mcbg","mcsg"]:
        sigma, variance_raw = er.errStat(source,returnCovar=True)
        # reshape 4x3x3 to 12x12
        variance = np.zeros([12,12])
        for c in range(4):
            for i in range(3):
                for j in range(3):
                    variance[c*3+i,c*3+j] = variance_raw[c,i,j]
                    
        stat_sigma.append(sigma)
        stat_covar.append(variance)

    stat_sigma = np.array(stat_sigma)  
    stat_covar = np.array(stat_covar) 

    er.io_printErrorForExcelFormat(stat_sigma.transpose(1,0,2))

    s = stat_sigma.shape
    stat_sigma = stat_sigma.reshape(s[0],s[1]*s[2])

    baseDir = common.getBaseDirectory() 
    np.save(baseDir+'/data/combine/stat_sigma',stat_sigma)
    np.save(baseDir+'/data/combine/stat_covar',stat_covar)

saveStatError(er)

relative statistical uncertainty [%]
0.553,0.517,1.217, 0.982,0.869,2.021, 0.710,0.552,1.447, 1.234,0.968,2.456
0.135,0.546,0.592, 0.141,0.517,0.639, 0.639,0.178,0.694, 0.594,0.178,0.725
0.266,0.227,0.570, 0.462,0.393,0.925, 0.323,0.264,0.690, 0.569,0.451,1.116


### 2.2 Systematical Uncertainty

In [6]:
def saveSystError(er):
    print( "relative systematics uncertainty [%]")
    syst_sigma, syst_covar = [],[]

    for source in ["BtmUp","BteUp"]:
        sigma = er.errConstent(source)
        variance = np.outer(sigma.reshape(1,12),sigma.reshape(1,12))
        syst_sigma.append(sigma)
        syst_covar.append(variance)
        
    for source in ["lumin","mctt","mctw","mcw",'mcz','mcvv',
                   "fakee","fakemu","fakeetau","fakemutau"]:
        sigma = er.errSystem_crossSection(source)
        variance = np.outer(sigma.reshape(1,12),sigma.reshape(1,12))
        syst_sigma.append(sigma)
        syst_covar.append(variance)
        
        
    for source in ["TopPtReweight","ERecoEff","EIDEff","MuRecoEff","MuIDEff","TauIDEff","JetToTauIDEff",
                   "EPt","MuPt","Tau0Pt","Tau1Pt","Tau10Pt",
                  ]:
        sigma = er.errSystem_downVariation(source)
        variance = np.outer(sigma.reshape(1,12),sigma.reshape(1,12))
        syst_sigma.append(sigma)
        syst_covar.append(variance)
        
    for source in ["tauReweight1000","tauReweight11000","tauReweight21000",
                   "tauReweight3000","tauReweight13000"
                  ]:
        sigma = er.errSystem_upDownVariation(source)
        variance = np.outer(sigma.reshape(1,12),sigma.reshape(1,12))
        syst_sigma.append(sigma)
        syst_covar.append(variance)
        
        
    for source in ["Pileup","JES","JER","BTag","Mistag","fsr"]:
        sigma = er.errSystem_upDownVariation(source)
        variance = np.outer(sigma.reshape(1,12), sigma.reshape(1,12))
        syst_sigma.append(sigma)
        syst_covar.append(variance)      
    
#     for source in ["fsr","isr","ue","meps"]:
#         sigma = er.errSystem_upDownVariationCutResidue(source,cutResidue=3)
#         variance = np.outer(sigma.reshape(1,12), sigma.reshape(1,12))
#         syst_sigma.append(sigma)
#         syst_covar.append(variance) 
    
    syst_sigma = np.array(syst_sigma) 
    syst_covar = np.array(syst_covar) 

    er.io_printErrorForExcelFormat(syst_sigma.transpose(1,0,2))

    s = syst_sigma.shape
    syst_sigma = syst_sigma.reshape(s[0],s[1]*s[2])

    baseDir = common.getBaseDirectory() 
    np.save(baseDir+'/data/combine/syst_sigma',syst_sigma)
    np.save(baseDir+'/data/combine/syst_covar',syst_covar)

saveSystError(er)

relative systematics uncertainty [%]
0.005,0.049,0.073, 0.005,0.048,0.074, 0.007,0.048,0.073, 0.007,0.048,0.074
0.027,0.010,0.057, 0.028,0.010,0.058, 0.024,0.007,0.057, 0.024,0.008,0.059
0.151,0.266,0.030, 0.048,0.072,0.006, 0.140,0.141,0.067, 0.008,0.049,0.003
0.011,0.003,0.100, 0.002,0.011,0.050, 0.008,0.009,0.106, 0.001,0.000,0.006
0.012,0.003,0.105, 0.002,0.011,0.052, 0.009,0.009,0.110, 0.001,0.000,0.007
0.157,0.157,0.144, 0.052,0.052,0.039, 0.149,0.153,0.159, 0.048,0.048,0.071
0.291,1.361,0.159, 0.089,0.382,0.051, 0.844,0.258,0.043, 0.120,0.098,0.127
0.001,0.020,0.011, 0.001,0.008,0.004, 0.017,0.001,0.008, 0.006,0.001,0.001
0.000,0.000,0.000, 0.000,0.000,0.000, 0.366,0.369,0.756, 0.194,0.190,0.336
0.626,0.602,1.231, 0.405,0.386,0.677, 0.000,0.000,0.000, 0.000,0.000,0.000
0.000,0.000,0.000, 0.000,0.000,0.000, 0.247,0.334,1.797, 0.139,0.189,1.029
0.257,0.347,1.766, 0.151,0.201,1.044, 0.000,0.000,0.000, 0.000,0.000,0.000
0.002,0.001,0.021, 0.000,0.002,0.011, 0.002,0.002,0.022, 0.000,

# 3. output Latex Table

In [8]:
%run -i '../scripts/note_uncertainty.py'

In [ ]:
#     for source in ["e","mu","tauID",'jetMisTauID']:
#         sigma = er.errSystem_objectEff(source)
#         variance = np.outer(sigma.reshape(1,12),sigma.reshape(1,12))
#         syst_sigma.append(sigma)
#         syst_covar.append(variance)

In [7]:
sigma = er.errSystem_upDownVariation("fsr")
sigma/0.108*100

array([[-0.7546923 , -0.56336153, -0.78828602],
       [-0.47845538, -0.79648906, -0.80230501],
       [-0.79487902, -0.42558462, -0.6127878 ],
       [-1.07588   , -1.00108001, -1.38707   ]])

In [13]:
sigma = er.errSystem_upDownVariation("isr")
sigma/0.108*100

array([[ 0.61298784,  0.65726433,  1.38221063],
       [ 0.92377239,  0.81140687,  0.91615779],
       [ 0.10179913,  1.07960526,  0.69728675],
       [ 0.13846273,  0.67379168, -0.1033589 ]])

In [15]:
sigma = er.errSystem_upDownVariationCutResidue("isr",3)
sigma/0.108*100

array([[0.47650823, 0.46227043, 0.93861782],
       [0.59470542, 0.33422956, 0.60685315],
       [0.43530199, 0.43752446, 0.90269255],
       [0.06995709, 0.06794519, 0.12052818]])

In [43]:
counts = pd.read_pickle( "../data/counts/count_.pkl")

In [77]:
counts0 = pd.read_pickle( "../data/counts/count_isrDown.pkl")
counts1 = pd.read_pickle( "../data/counts/count_isrUp.pkl")

In [68]:
tr,ch,mc = 0,3,1

acc = common.matrixToArray(counts.acc[tr][ch][mc])
accUp = common.matrixToArray(counts1.acc[tr][ch][mc])
accDown = common.matrixToArray(counts0.acc[tr][ch][mc])

accVar = common.matrixToArray(counts.accVar[tr][ch][mc])
accUpVar = common.matrixToArray(counts1.accVar[tr][ch][mc])
accDownVar = common.matrixToArray(counts0.accVar[tr][ch][mc])

resUp = abs(accUp-acc)/(accVar+accUpVar)**0.5
resDown = abs(accDown-acc)/(accVar+accDownVar)**0.5

name = common.WWBranchNames()
for i in range(21):
    sfUp,sfDown = 0,0
    if resUp[i] > 3:
        sfUp = accUp[i]/acc[i]
        sfDown = accDown[i]/acc[i]
    print("{:20}: {:5.3f}, {:5.3f}".format(name[i],sfUp,sfDown))

$ee$                : 0.000, 0.000
$\mu\mu$            : 0.962, 1.010
$e\mu$              : 0.945, 1.022
$\tau_e\tau_e$      : 0.000, 0.000
$\tau_\mu\tau_\mu$  : 0.000, 0.000
$\tau_e\tau_\mu$    : 0.000, 0.000
$\tau_e\tau_h$      : 0.000, 0.000
$\tau_\mu\tau_h$    : 0.000, 0.000
$\tau_h\tau_h$      : 0.000, 0.000
$e\tau_e$           : 0.000, 0.000
$e\tau_\mu$         : 0.000, 0.000
$e\tau_h$           : 0.000, 0.000
$\mu\tau_e$         : 0.920, 1.040
$\mu\tau_\mu$       : 0.943, 1.023
$\mu\tau_h$         : 0.931, 1.033
$eh$                : 0.528, 1.388
$\mu h$             : 0.916, 1.051
$\tau_eh$           : 0.000, 0.000
$\tau_\mu h$        : 0.920, 1.060
$\tau_hh$           : 0.573, 1.419
$hh$                : 0.502, 1.457


In [88]:
tr = 3
acc = counts.acc[tr].copy()
acc1 = counts1.acc[tr].copy()
acc0 = counts0.acc[tr].copy()

acc01 = (acc1*1/3+acc0*2/3)

accVar = counts.accVar[tr].copy()
acc1Var = counts1.accVar[tr].copy()
acc0Var = counts0.accVar[tr].copy()

res1 = abs(acc1-acc)/(accVar+acc1Var)**0.5
res0 = abs(acc0-acc)/(accVar+acc0Var)**0.5
res01 = abs(acc0-acc1)/(acc1Var+acc0Var)**0.5

for ch in range(4):
    mc=1
    for i in range(6):
        for j in range(6):
            if res01[ch,mc][i,j]<3:
                acc1[ch,mc][i,j] = acc01[ch,mc][i,j]
                acc0[ch,mc][i,j] = acc01[ch,mc][i,j]

In [89]:
# up tuning
slv1 = BFSolver3D( np.sum(acc1*er.ca,axis=1) )
BW1  = slv1.solveQuadEqn(slv1.setMeasuredX(nData=counts1.ndata[tr], nMcbg=counts1.nmcbg[tr].dot(np.ones(3))+counts1.nfake[tr]))
# down tuning
slv2 = BFSolver3D( np.sum(acc0*er.ca,axis=1) )
BW2  = slv2.solveQuadEqn(slv2.setMeasuredX(nData=counts0.ndata[tr], nMcbg=counts0.nmcbg[tr].dot(np.ones(3))+counts0.nfake[tr]))
# differentce between up and down tuning
print((BW1-BW2)/2/0.1080*100)

[0.0988434  0.09565056 0.17098258]


In [85]:
print(counts.ndata[0]-counts0.ndata[0])
print(counts.nmcbg[0]-counts0.nmcbg[0])
print(counts.nfake[0]-counts0.nfake[0])

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0.]


In [24]:
counts1.accVar[0][3][1]**0.5/counts1.acc[0][3][1]

array([[1.23812276e+00, 5.44267664e-03,            inf, 2.26110848e-02,
        6.02663712e-01, 1.20661118e-01],
       [5.44267664e-03, 7.80294975e-03, 1.27426556e-02, 1.38241656e-02,
        5.41245226e-03, 1.07055726e-03],
       [           inf, 1.27426556e-02,            inf, 5.33164419e-02,
                   inf, 2.40599071e-01],
       [2.26110848e-02, 1.38241656e-02, 5.33164419e-02, 6.28052574e-02,
        2.26312636e-02, 4.59895401e-03],
       [6.02663712e-01, 5.41245226e-03,            inf, 2.26312636e-02,
        4.35954570e-01, 1.03693105e-01],
       [1.20661118e-01, 1.07055726e-03, 2.40599071e-01, 4.59895401e-03,
        1.03693105e-01, 3.80247767e-02]])

In [2]:
sigma, variance_raw = er.errStat("mcsg",returnCovar=True)

In [4]:
sigma/0.108*100

array([[0.53401089, 0.45867545, 1.15690868],
       [0.95222688, 0.80551395, 1.82853771],
       [0.64549883, 0.52774019, 1.38175311],
       [1.2019165 , 0.93939064, 2.2449766 ]])